FROM alpine:3.14.10

WORKDIR /app

COPY build/drogua /app/drogua
COPY lib/ /app/lib/
COPY app.lua /app/app.lua
COPY config.json /app/config.json

RUN chmod +x /app/drogua

EXPOSE 5555

CMD ["/app/drogua"]
